### PR TITLE
use promise instead of callback

### PR DESCRIPTION
**Pull request by Robbilie**

### CODE REVIEW

**Comment by rom1504** [comment]
It's not enough
See https://github.com/TheDudeFromCI/mineflayer-utils/blob/master/src/classes/taskQueue.ts

Callbacks have an err as first argument which is a promise reject and must be translated that way

**Comment by Robbilie** [comment]
Yeah I figured, just wanted to check if the pipeline would run, gotta invest a little more time...

**Comment by Robbilie** [comment]
should work this way…?

**Comment by rom1504** [comment]
yes

if you want to do it properly, I'd suggest changing this as well https://github.com/TheDudeFromCI/mineflayer-utils/blob/master/src/classes/taskQueue.ts (or maybe stop depending on it)

**Pull request merged**
